"""Start

Revision ID: 8ca3d3c445a4
Revises: 
Create Date: 2023-10-30 08:40:17.656178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca3d3c445a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    subscription_type = op.create_table('subscription_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    trainer = op.create_table('trainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('img_path', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    info_trainer = op.create_table('info_trainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    opportunity = op.create_table('opportunity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subscription_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_type_id'], ['subscription_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    user = op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('sub_id', sa.Integer(), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sub_id'], ['subscription_type.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.bulk_insert(
        subscription_type,
        [
            {"id": 1, "name": "Максимум", "price": 2500.0},
            {"id": 2, "name": "Стандарт", "price": 2200.0},
            {"id": 3, "name": "Лайт", "price": 1700.0}
        ]
    )

    op.bulk_insert(
        opportunity, 
        [
            {"id": 1, "name": "Безлимитный доступ", "subscription_type_id": 1},
            {"id": 2, "name": "4 гостевых визита ежемесячно", "subscription_type_id": 1},
            {"id": 3, "name": "Тренажерный зал", "subscription_type_id": 1},
            {"id": 4, "name": "Групповые тренировки", "subscription_type_id": 1},
            {"id": 5, "name": "Регулярный анализ состава тела", "subscription_type_id": 1},
            {"id": 6, "name": "Персональная тренировка с тренером", "subscription_type_id": 1},
            {"id": 7, "name": "Финские сауны и хаммам", "subscription_type_id": 1},

            {"id": 8, "name": "Безлимитный доступ", "subscription_type_id": 2},
            {"id": 9, "name": "Тренажерный зал", "subscription_type_id": 2},
            {"id": 10, "name": "Групповые тренировки", "subscription_type_id": 2},
            {"id": 11, "name": "Регулярный анализ состава тела", "subscription_type_id": 2},
            {"id": 12, "name": "Персональная тренировка с тренером", "subscription_type_id": 2},
            {"id": 13, "name": "Финские сауны и хаммам", "subscription_type_id": 2},

            {"id": 14, "name": "Доступ в клуб не более 6 раз в месяц", "subscription_type_id": 3},
            {"id": 15, "name": "Тренажерный зал", "subscription_type_id": 3},
            {"id": 16, "name": "Групповые тренировки", "subscription_type_id": 3},
            {"id": 17, "name": "Регулярный анализ состава тела", "subscription_type_id": 3},
            {"id": 18, "name": "Персональная тренировка с тренером", "subscription_type_id": 3},
            {"id": 19, "name": "Финские сауны и хаммам", "subscription_type_id": 3}
        ]
    )




    op.bulk_insert(
        trainer,
        [
            {"id": 1, "name": "Дмитрий", "price": 2500.0, "img_path": "trainer_1", "age": 35},
            {"id": 2, "name": "Виктория", "price": 2200.0, "img_path": "trainer_2", "age": 25},
            {"id": 3, "name": "Николай", "price": 1700.0, "img_path": "trainer_3", "age": 37},
            {"id": 4, "name": "Михаил", "price": 3000.0, "img_path": "trainer_4", "age": 44},
            {"id": 5, "name": "Валентин", "price": 2200.0, "img_path": "trainer_5", "age": 29}
        ]
    )

    op.bulk_insert(
        info_trainer, 
        [
            {"id": 1, "name": "Стаж более 6 лет", "trainer_id": 1},
            {"id": 2, "name": "Мастер спорта по легкой атлетике", "trainer_id": 1},

            {"id": 3, "name": "Стаж более 4 лет", "trainer_id": 2},
            {"id": 4, "name": "Заслуженный тренер России по художественной гимнастике", "trainer_id": 2},

            {"id": 5, "name": "Стаж более 7 лет", "trainer_id": 3},
            {"id": 6, "name": "Мастер спорта по боксу", "trainer_id": 3},

            {"id": 7, "name": "Стаж более 10 лет", "trainer_id": 4},
            {"id": 8, "name": "Мастер спорта по бодибилдингу", "trainer_id": 4},

            {"id": 9, "name": "Стаж более 5 лет", "trainer_id": 5},
            {"id": 10, "name": "Мастер спорта по кроссфиту", "trainer_id": 5}
        ]
    )


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('opportunity')
    op.drop_table('info_trainer')
    op.drop_table('trainer')
    op.drop_table('subscription_type')
    # ### end Alembic commands ###
